### ISSUE TITLE
How to use it in a build project？

### ISSUE THREAD

**Issue by 494311870** [H1M4W4R1/Unity-Aspect-Oriented-Programming#3]
In the editor, everything was fine, but when I built an Android project, the code didn't seem to be injected.
What is the right way to use it?

**Comment by H1M4W4R1** [comment]
I don't use Android (imo it s***s), so I don't know how the build pipeline for Android looks like. It probably recompiles code from C# to Java and then converts it to DEX then there's no way to make it work, cuz this API does not use CastleProxy, which is quite insecure, but it recompiles *.dll (precisely Assembly-CSharp.dll inside Library folder).

ATM I'm quite overloaded with work, so I don't know when I'll find time to check this out.

**Comment by 494311870** [comment]
I've tried something，it seems really cannot be used in Android.Thank you very much.If I can make it, I'll tell you.

**Comment by 494311870** [comment]
Use `UnityEditor.Build.IFilterBuildAssemblies` can weave assemblies on build.

public string[] OnFilterAssemblies(BuildOptions buildOptions, string[] assemblies)
{

}

**Comment by H1M4W4R1** [comment]
Yep, it works. Thanks ;)
